### ISSUE TITLE
Duplicated key *url* in meta.yaml

### ISSUE THREAD

**Issue by msviridov-rocket** [conda-forge/pandas-feedstock#67]
When trying to process meta.yaml using ruamel_yaml it shows a error. It can be suppressed now, but it will become a real error in future. If you want to use several sources you have to use a list like that:
```
source:
  - url: <first url here>
    sha256: <checksum for the url above>
  - url: <second url here>
```
Otherwise YAML parsers raise DuplicatedKeyError or another exception with the same meaning.
